spring:
  application:
    name: server
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database: postgresql
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgresql
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
      ssl:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ADMIN_EMAIL}
    password: ${ADMIN_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh

jwt:
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  secretKey: ${JWT_SECRET_KEY}
  refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
  issuer: tanh.io
